### ISSUE TITLE
Cant set user prefix for lib path

### ISSUE THREAD

**Issue by D4wN** [Loremipsum1988/tinkervision#5]
_vision_lib_set_user_prefix _returns Error(-3 = TV_INVALID_ARGUMENT)

Tested with [TinkervisionPlayground.zip](https://github.com/Loremipsum1988/tinkervision/files/156869/TinkervisionPlayground.zip) in modules.Function[83, 40]

**Comment by Loremipsum1988** [comment]
The following subdirectories must exist in the new path
lib, data, scripts
